[package]
name = "deoptimizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
capstone = "0.11.0"
chrono = "0.4.31"
clap = { version = "4.4.7", features = ["derive"] }
colored = "2.0.4"
ctrlc = "3.4.1"
hexdump = "0.1.1"
keystone = "0.9.0"
log = "0.4.20"
thiserror = "1.0.50"
