name: macos-build

on:
  workflow_dispatch:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: RUSTFLAGS="-C target-feature=+crt-static" cargo build --release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: deoptimizer 
        path: ./target/release/deoptimizer
        retention-days: 5

